version: "3.3"
services:
  builder:
    container_name: aosp_builder
    hostname: aosp-builder
    build: ./build
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro
      - ~/.git-credentials:/home/ubuntu/.git-credentials:ro
      - ~/.cache/ccache/:/ccache:rw
      - /Developer/AOSP:/AOSP:rw

    
  
